sonar.projectKey=sonar-test-github
sonar.projectName=Sonar Test GitHub
sonar.sources=src
sonar.language=java
sonar.java.binaries=.
sonar.host.url=http://100.50.24.41:9000
sonar.login=squ_42fa5edc60add6ed2fca8a117848dd6a084831e0
