sonar.projectKey=sonar-demo-app
sonar.projectName=sonar-demo-app
sonar.sources=src
sonar.language=java
sonar.java.binaries=.
sonar.host.url=http://100.50.24.41:9000
sonar.login=sqp_090ab245624d1037c79fb41831664bcdfbd10da8
