sonar.projectKey=sonar-demo-app
sonar.projectName=New-project
sonar.sources=src
sonar.language=java
sonar.java.binaries=.
sonar.host.url=http://52.91.192.143:9000
sonar.login=sqp_090ab245624d1037c79fb41831664bcdfbd10da8
